<header>
    <h2>Rédiger un nouvel article</h2>
</header>
<section>
    <form action="<?=buildUrl('/admin/post/new');?>" method="post" enctype="multipart/form-data">
    <?php if (isset($error)) : ?>
            <p class="error"><?= $error; ?></p>
        <?php endif; ?>
        <fieldset>
            <div>
                <label for="name">Titre</label>
                <input type="text" id="name" name="name">
            </div>
            <div>
                <label for="category">Catégorie</label>
                <select name="category">
                    <?php foreach($categories as $category): ?>
                        <option value="<?=$category['id'];?>"><?=$category['name'];?></option>
                    <?php endforeach; ?>
                </select>
            </div>
            <div>
            <input type="file" name="fileToUpload" id="fileToUpload">
            </div>
            <div>
                <label for="content">Contenu</label>
                <textarea id="content" name="content"></textarea>
            </div>
        </fieldset>
        <input type="submit" value="Enregistrer">
    </form>

</section>