<header>
    <h2>Ajouter un nouveau jeu</h2>
</header>
<section>
    <form action="<?= buildUrl('/admin/game/new'); ?>" method="post">

        <?php if (isset($error)) : ?>
            <p class="error"><?= $error; ?></p>
        <?php endif; ?>

        <fieldset>
            <!-- NOM DU JEU-->
            <div>
                <label for="name">Titre</label>
                <input type="text" id="name" name="name">
            </div>
            <!--NOM DU JEU -->


            <!-- EXTENSION-->
            <div>
                <label for="extension">extension</label>
                <input type="text" id="extension" name="extension">
            </div>



            <!-- DIFFICULTE-->
            <div>
                <label for="difficulty">Difficulté</label>
                <select name="difficulty">
                    <option value="">--Please choose an option--</option>
                    <option value="1">1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                    <option value="4">4</option>
                    <option value="5">5</option>
                    <option value="6">6</option>
                    <option value="7">7</option>
                    <option value="8">8</option>
                    <option value="9">9</option>
                    <option value="10">10</option>

                </select>

                <label for="difficulty_max">Difficulté</label>
                <select name="difficulty_max">
                    <option value="0">--Please choose an option--</option>
                    <option value="1">1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                    <option value="4">4</option>
                    <option value="5">5</option>
                    <option value="6">6</option>
                    <option value="7">7</option>
                    <option value="8">8</option>
                    <option value="9">9</option>
                    <option value="10">10</option>
                </select>
            </div>
            <!--DIFFICULTE -->

            <!-- temps-->
            <div>
                <label for="time">Temps de jeu minimum</label>
                <!--<input type="number" id="time" name="time" min="1" max="10"> -->
                <input id="time" type="time" name="time" min="00:05" max="20:00" required pattern="[0-9]{2}:[0-9]{2}">
            </div>


            <div>
                <label for="time_max">Temps de jeu maximum</label>
                <!-- <input type="number" id="time_max" name="time_max" min="1" max="10"> -->
                <input id="time_max" type="time" name="time_max" min="00:05" max="20:00" pattern="[0-9]{2}:[0-9]{2}">
            </div>
            <!-- temps-->

            <!-- NOMBRE DE JOUEURS-->
            <div>
                <label for="player">player</label>
                <select name="player">
                    <option value="">--Please choose an option--</option>
                    <option value="1">1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                    <option value="4">4</option>
                    <option value="5">5</option>
                    <option value="6">6</option>
                    <option value="7">7</option>
                    <option value="8">8</option>
                    <option value="9">9</option>
                    <option value="10">10</option>
                </select>

                <label for="player_max">player max</label>
                <select name="player_max">
                    <option value="0">--Please choose an option--</option>
                    <option value="1">1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                    <option value="4">4</option>
                    <option value="5">5</option>
                    <option value="6">6</option>
                    <option value="7">7</option>
                    <option value="8">8</option>
                    <option value="9">9</option>
                    <option value="10">10</option>
                </select>
            </div>
            <!-- NOMBRE DE JOUEURS-->

            <!-- AGE MINIMUM-->
            <div>
                <label for="age">Age</label>
                <input type="text" id="age" name="age">
            </div>
            <!-- AGE MINIMUM-->


        </fieldset>

        <input type="submit" value="Enregistrer">

    </form>

</section>