<header>
    <h2>Administration</h2>
</header>
<section>
    <!-- On mettra ici un tableau avec la liste des articles -->

    <!-- Affichage le cas échéant des messages de confirmation -->
    <?php include VIEWS_DIR . '/inc/flash_messages.phtml'; ?>

    <table>
        <thead>
            <th scope="col">identifiant</th>
            <th scope="col">status</th>
            <th scope="col">Sujet</th>
            <th scope="col">Crée le</th>
            <th scope="col">Nom prénom</th>
            <th scope="col">message</th>
        </thead>
        <tbody>
            <?php foreach ($requests as $request) : ?>
                <tr>
                    <td><?= htmlspecialchars(formatDate($request['id_request'])); ?></td>
                    <td><?= htmlspecialchars($request['firstname']) . " " .  htmlspecialchars($request['lastname']); ?></td>
                    <td><?= htmlspecialchars($request['subject_label']); ?></td>
                    <td><?= htmlspecialchars($request['createdAt']); ?></td>
                    <td><?= htmlspecialchars($request['firstname']); ?></td>

                    <td><?= htmlspecialchars(mb_substr($request['content'], 0, 150, 'UTF-8')); ?></td>
                    <td>
                        <a href="<?= buildUrl('/admin/request/edit', ['id_request' => $request['id_request']]); ?>" title="Modifier l'article">
                            <i class="fas fa-pen-square"></i>
                        </a>
                        <a href="<?= buildUrl('/admin/request/delete', ['id_request' => $request['id_request']]); ?>" title="Supprimer l'article">
                            <i class="fas fa-trash-alt"></i>
                        </a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</section>