<!-- PAGE D'ACCUEIL-->

<!--BANDEAU PRÉSENTATION + HORAIRES-->
<section class="section-introduction">

    <!-- MESSAGE BIENVENUE-->
    <div class="welcome-message">
        <h3 class="heading-tertiary"> Bienvenue Chez Mellie votre Salon de Thé à Mauriac</h3>
        <p>«Chez Mellie» c'est un Salon de Thé, simple et chaleureux avec ses cookies et financiers faits maison (par Mellie elle-même!), un espace de douceur pour se marrer, profiter, se détendre en solo, entre amis ou en famille. </p>
    </div>
    <!-- HORAIRES-->
    <div class="schedule-box">
        <h3 class="heading-tertiary">Horaires du magasin</h3>
        <table>
            <tbody>
                <tr>
                    <td>Semaine: </td>
                    <td> 8H - 18H</td>
                </tr>
                <tr>
                    <td>Samedi: </td>
                    <td></td>
                </tr>
                <tr>
                    <td>Dimanche: </td>
                    <td> FERME</td>
                </tr>
            </tbody>
        </table>
    </div>
</section>


<!-- MENU-->
<section class="section-menu">
    <div class="menu" data-aos="fade-left">
        <h2 class="heading-secondary">Vous voulez Manger à Mauriac ?</h2>
        <img src="https://img.icons8.com/dusk/64/000000/paella.png" class="menu__logo" />
        <p class="menu__paragraph"><span class="bold">Les midis, Chez Mellie vous propose sa
                formule du jour</span>, toujours fait maison, avec les produits de nos partenaires producteurs. Chez Mellie, on sort du traditionnel « aligot saucisse » et on aime manger local en variant les saveurs !
            Chez Mellie s'adapte à vos envies :
        <ul class="menu__list">
            <li> <span class="bold">Formule sur place</span> dans une ambiance chaleureuse</li>
            <li> <span class="bold">Vente à emporter</span> pour savourer votre repas et profiter des paysages du Cantal</li>
            <li> Restaurant adapté aux enfants avec une formule spéciale et un coin jeux.</li>
            <li> Mangez <span class="bold">végétarien</span> dans le Cantal ? C'est possible Chez Mellie, j'adapte la formule pour vous quand je suis prévenue.</li>
            <li>Repartez avec des gourmandises des artisans du Cantal et de la Corrèze : <span class="bold">cookies, sirops, confitures</span>, ...</li>
        </ul>
        </p>
    </div>
</section>
</div>

<!-- NOS ENGAGEMENTS-->
<section class="section-engagement">
    <h3 class="heading-secondary">Nos engagements </h3>
    <div class="feature-box">
        <svg class="feature-box__svg">

            <use xlink:href=" <?= asset('img/sprite.svg#icon-home') ?>"></use>
        </svg>
        <p class="feature-box__text">
            Soutenir les producteurs du territoire cantalien
        </p>
    </div>
    <div class="feature-box">
        <svg class="feature-box__svg">

            <use xlink:href="<?= asset('img/sprite.svg#icon-tag') ?>"></use>
        </svg>
        <p class="feature-box__text">
            Des prix justes du producteur au consommateur
        </p>
    </div>
    <div class="feature-box">
        <svg class="feature-box__svg">

            <use xlink:href="<?= asset('img/sprite.svg#icon-heart') ?>"></use>
        </svg>
        <p class="feature-box__text">
            Un lieu convivial de conseil et de partage
        </p>
    </div>
</section>

<!-- NEWSLETTER-->
<section class="section-newsletter">
    <div class="section-newsletter__body" data-aos="fade-right">
        <h4 class="heading-secondary">Newsletter</h4>
        <div>
            <p>Recevez les animations et les infos du Salon en cliquant sur l'icône</p>
            <div class="section-newsletter__logo">
                <a href="https://gmail.us10.list-manage.com/subscribe?u=11bd8e48ef4710863cde5ef5e&id=1e0ae2d2cc" target="_blank"> <img src="https://img.icons8.com/clouds/100/000000/mailbox-plane.png" />
                </a>
            </div>
        </div>
    </div>
</section>



<!--FIN PAGE D'ACCUEIL -->