<!-- ONGLET ARTICLES -->

<!-- CHARGEMENT INSTAGRAM ELFSIGHT -->
<script src="https://apps.elfsight.com/p/platform.js" defer></script>
<div class="elfsight-app-aad980fa-2ada-4adc-952d-1ecaeaa1e980"></div>

<!-- PARTIE NEWS FILTRE  +  DISPLAY -->
<div class="news-section">

    <!-- FILTRES NEWS -->
    <div class="news-selection">
        <div class="news-selection__filtres">
            <ul class="news-selection__list">
                <li class="filtre select news-selection__list-item" data-filtre="all">Tout</li>
                <?php foreach ($categories as $categorie) : ?>
                    <li class="filtre news-selection__list-item" data-filtre="<?= strtolower($categorie['name']); ?>"><?= strtolower($categorie['name']); ?></li>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>

    <!-- CONTAINER DE NEWS -->
    <div class="news-display">
        <?php foreach ($news as $new) : ?>

            <!-- UNE NEWS -->
            <div class="<?= htmlspecialchars(mb_substr($new['name'], 0, 500, 'UTF-8')); ?> card" data-aos="fade-down">


                <div class="thumbnail"><img class="thumbnail__img" src="<?= asset('img/news/' . htmlspecialchars($new['image'])) ?>" /></div>
                <div class="card-content">
                    <h1><?= htmlspecialchars($new['title']); ?></h1>

                    <div class="card-content__date">
                        <h2><time datetime="<?= htmlspecialchars($new['createdAt']); ?>"><?= date('d/m/Y', strtotime(htmlspecialchars($new['createdAt']))); ?></time></h2>
                    </div>
                    <p class="card-content__text"><?= htmlspecialchars(mb_substr($new['content'], 0, 5000, 'UTF-8')); ?></p>
                    <p class="card-content__hashtag">#<?= htmlspecialchars(mb_substr($new['name'], 0, 500, 'UTF-8')); ?></p>
                </div>
            </div>
        <?php endforeach; ?>
    </div>

</div>