<!-- Affichage le cas échéant des messages de confirmation -->
<?php include VIEWS_DIR . '/inc/flash_messages.phtml'; ?>

<h2>Formulaire de contact</h2>
<form action="<?= buildUrl('/add_request'); ?>" method="post">
    <div>
        <label for="name">Nom :</label>
        <input type="text" id="name" name="name">
    </div>

    <div>
        <label for="firstname">Prénom :</label>
        <input type="text" id="name" name="firstname">
    </div>

    <div>
        <label for="mail">e-mail :</label>
        <input type="email" id="mail" name="mail">
    </div>

    <div>
        <label for="phone">Téléphone :</label>
        <input type="text" id="phone" name="phone">
    </div>

    <div>
        <label for="subject">Choisir une option:</label>
        <select name="subject" id="subject">
            <option value="">--Choisissez--</option>
            <?php foreach ($subjects as $subject) : ?>
                <option value="<?= htmlspecialchars($subject['id_subject']); ?>"><?= htmlspecialchars($subject['subject_label']); ?></option>
            <?php endforeach; ?>

        </select>
    </div>

    <div>
        <label for="msg">Message :</label>
        <textarea id="msg" name="message"></textarea>
    </div>



    <input type="submit" value="Envoyer le formulaire">


</form>