<!--PAGE DES THÉS-->
<div class="tea-background">
    <!-- MOT DE MELLIE-->
    <div class="mellie-word">
        <h3 class="heading-tertiary">Le mot de Mellie</h3>
        <p>Ce qui me rend heureuse, c'est de voir les yeux de mes clientes se régaler ! Qu'elles soient fidèles à leur infusion fétiche ou plus aventurière à découvrir la richesse et la diversités des parfums du Salon de thé, je guette cette lueur qui fait « miam » dans le regard ! 
            Thé vert, noir, blanc, infusions... chacun a ses bienfaits et ses propriétés. Je les ai sélectionnés pour leur qualité évidemment mais aussi pour leur parfum et la générosité de leurs saveurs.
            Pour tous ceux qui aiment profiter de l'instant, (et j'en fais partie!) je ne pouvais envisager Chez Mellie sans ses Cookies et ses Financiers ! Ce sont les gourmandises préparées par mes soins que vous retrouverez tout au long de l'année, avec leur panel de parfums pour satisfaire les plus petits comme les grands.
            Je vous souhaite un très bon moment dans votre Salon de thé, ou une super pause parfumée dans votre canapé ! 
        </p>
    </div>


    <!-- FILTRATION DES THÉS-->
    <div class="tea-selection">
        <h2 class="heading-secondary">Notre carte de thés</h2>
        <p class="tea-selection__text"> Pour découvrir et choisir vos saveurs préférées disponibles au Salon de thé Chez Mellie à Mauriac, cliquez sur les images ci-dessous.</p>
        <div class="tea-selection__filtre">
            <ul class="tea-selection__list">
                <li class="filtre select tea-selection__list-item" data-filtre="all">Tout</li>
                <li class="filtre tea-selection__list-item" data-filtre="Vert">vert</li>
                <li class="filtre tea-selection__list-item" data-filtre="Blanc">blanc</li>
                <li class="filtre tea-selection__list-item" data-filtre="noir">noir</li>
                <li class="filtre tea-selection__list-item" data-filtre="Rooibos">rooibos</li>
                <li class="filtre tea-selection__list-item" data-filtre="Infusion">infu</li>
            </ul>
        </div>
    </div>

    <!-- CONTAINER DE THÉS-->
    <div class="tea-container">
        <?php foreach ($posts as $post) : ?>
            <!-- UN THÉ-->
            <div class="<?= htmlspecialchars($post['color']); ?> tea-card">
                <div class="tea-card__side tea-card__side--front">
                    <div class="tea-card__picture">
                        <img class="tea-card__img" src="
                        <?= asset('img/the/' . htmlspecialchars($post['image'])) ?>" alt="texte alternatif">
                    </div>
                    <h4 class="tea-card__heading">
                        <span class="tea-card__heading-span"><?= htmlspecialchars($post['name']); ?></span>
                    </h4>
                    <div class="tea-card__details">

                        <p><?= htmlspecialchars(mb_substr($post['description'], 0)); ?>
                        <div <?= strtolower(htmlspecialchars($post['color'])); ?>">
                        </div>

                    </div>
                </div>
                <div class="tea-card__side tea-card__side--back tea-card__side--back-1">
                    <div class="tea-card__cta">
                        <div class="tea-card__price-box">
                            <div class="tea-card__price-only">Sachet de 100g</div>
                            <div class="tea-card__price-value">6,00 €</div>

                        </div>
                        <a href="#popup<?= htmlspecialchars($post['teaid']); ?>" class="btn btn--white">Réservation</a>


                    </div>
                </div>
            </div>
            <!--POPUP DE RÉSERVATION DU THÉ -->
            <div class="popup" id="popup<?= htmlspecialchars($post['teaid']); ?>">
                <div class="popup__content">
                    <div class="popup__right">
                        <form class="popup-form hidden" id="form<?= htmlspecialchars($post['teaid']); ?>" action="<?= buildUrl('/ajax/tea'); ?>">
                            <h2 class="heading-secondary">Réservez votre thé</h2>
                            <h3>Nous vous contacterons si le thé n'est pas disponible</h3>
                            <div class="tea-form-group">
                                <label for="email" class="tea-form__label">Email</label>
                                <input type="email" class="tea-form__input" id="email<?= htmlspecialchars($post['teaid']); ?>" name="email" placeholder="E-mail">
                            </div>

                            <div class="tea-form-group named">
                                <label for="name"> ne pas remplir</label>
                                <input type="text" name="name" id="name<?= htmlspecialchars($post['teaid']); ?>" />
                            </div>

                            <div class="tea-form-group named">
                                <label for="theselected" class="tea-form__label">thé</label>
                                <textarea name="theselected" id="theselected<?= htmlspecialchars($post['teaid']); ?>" class="tea-form__input" placeholder="theselected"><?= htmlspecialchars($post['name']); ?></textarea>
                            </div>

                            <div class="tea-form-group">
                                <label for="<?= htmlspecialchars($post['color']); ?>quantity" class="tea-form__label">Quantité</label>
                                <input class="quantity" id="<?= htmlspecialchars($post['teaid']); ?>quantity" min="0" name="quantity" value="1" type="number">
                            </div>
                            <div class="tea-form-group">
                                <label for="message" class="tea-form__label">Message</label>
                                <textarea name="message" id="message<?= htmlspecialchars($post['teaid']); ?>" class="tea-form__input" placeholder="Message"></textarea>
                            </div>
                            <input type="submit" class="popup__yes" value="Envoyer le formulaire">
                            <a href="#" class="popup__close">Non</a>
                        </form>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
</div>
<!-- FIN ONGLET THE 
-->